### ISSUE TITLE
Authorization checklist

### ISSUE THREAD

**Issue by nstudt** [nstudt/corpin-emr#12]
- [ ] Login UI
- [ ] define passport LocalStrategy
- [ ] Route /login
- [ ] passport.authenticate()
- [ ] app.use check for authentication on all routers
- [ ] authorization check on records access.
- [ ] authorization check on admin access
- [ ] authorization check on write access
